services:
  fluxocaixawebapi:
    image: fluxocaixawebapi
    build:
      context: .
      dockerfile: src/Services/Presentation/FluxoCaixa.Presentation/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=desafio!123
      - ACCEPT_EULA=Y
    ports:
     - "1433:1433"